version: 2.1
orbs:
  # Dependencies required for the pipeline
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  # Stage 1 - Installing Dependencies, building, linting and running unit test cases
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      # Installing NodeJS
      - node/install:
          node-version: "14.15"
      # # Installing ChromeHeadless browser for testing
      # - browser-tools/install-chrome
      # - browser-tools/install-chromedriver
      # - checkout
      # # All stages below are self explanatory
      # - run:
      #     name: Install Front-End Dependencies
      #     command: |
      #       npm run frontend:install
      - run:
          name: Install API Dependencies
          command: |
            npm run api:install
      # - run:
      #     name: Front-End Lint
      #     command: |
      #       npm run frontend:lint
      # - run:
      #     name: Front-End Build
      #     command: |
      #       npm run frontend:build
      - run:
          name: API Build
          command: |
            npm run api:build
      # - run:
      #     name: Front-End Test
      #     command: |
      #       npm run frontend:test
      # Taking the workspace backup so we can use in deploy stage otherwise we need to repeat the steps again
      - persist_to_workspace:
          root: udagram
          paths:
            - udagram-frontend/www
            - udagram-api/www
  # Stage 3 - Deploying the build code to AWS S3 and EBS
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "14.15"
      - eb/setup
      - aws-cli/setup
      - checkout
      # Mounting the workspace from Stage 1
      - attach_workspace:
          at: udagram
      # Deploying the app
      - run:
          name: Deploy App
          command: |
            npm run deploy
workflows:
  udagram:
    jobs:
      - build
      # - hold:
      #     filters:
      #       branches:
      #         only:
      #           - main
      #     type: approval
      #     requires:
      #       - build
      - deploy:
          # Waiting for manual approval
          requires:
            - build
