version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  install:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: "14.15"
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            npm run frontend:install
      - run:
          name: Install API Dependencies
          command: |
            npm run api:install
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - checkout
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: API Build
          command: |
            npm run api:build
  lint:
    docker:
      - image: "cimg/base:lint"
    steps:
      - checkout
      - run:
          name: Front-End Lint
          command: |
            npm run frontend:lint
  test:
    docker:
      - image: "cimg/base:test"
    steps:
      - checkout
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "14.15"
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Deploy App
          command: |
            npm run deploy

workflows:
  udagram:
    jobs:
      - install
      - build
      - lint
      - test
      - hold:
          filters:
            branches:
              only:
                - main
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
